apiVersion: v1
kind: Service
metadata:
  name: advanced-app-service
  namespace: self-healing
  labels:
    app: advanced-app
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: advanced-app
